name: Deploy to AWS
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
      MY_NAME: TGSpooney
      AWS_REGION: eu-west-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean install dependencies
        run: npm ci
        working-directory: ./beth-site
      - name: Build react app
        run: npm run build
        working-directory: ./beth-site
      - name: Run tests
        run: npm run test
        working-directory: ./beth-site
      - name: Terraofrm init
        working-dirctory: ./terraform
        run: make init
      - name: Terraform plan
        working-directory: ./terraform
        run: make plan
      - name: Terraform apply
        working-directory: ./terraform
        run: make apply
